"use client";

import { useState, useCallback } from "react";
import { getRecentMoodHistory, getTriggerHistory } from "@/lib/storage";
import type { InsightsResponse } from "@/lib/schema";

interface ReportData extends InsightsResponse {}

export default function WeeklyReport() {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<ReportData | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchReport = useCallback(async () => {
    setLoading(true);
    setError(null);
    setOpen(true);

    const moodHistory = getRecentMoodHistory(7);
    const triggerHistory = getTriggerHistory().slice(-7);

    try {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          moodHistory,
          triggerHistory,
          examType: moodHistory[0]?.examType ?? "General",
        }),
      });

      const json = await res.json() as { success?: boolean; data?: ReportData; trend?: string; topTriggers?: string[]; tip?: string; encouragement?: string; error?: string };

      // Handle both new {success, data} shape and old direct shape
      const data = json.success ? json.data : (json.trend ? json : null);

      if (!data) {
        setError((json as { error?: string }).error ?? "Failed to generate report");
      } else {
        setReport(data as ReportData);
      }
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }, []);

  const downloadReport = useCallback(() => {
    if (!report) return;
    const text = [
      "MindEase Weekly Wellness Report",
      `Generated: ${new Date().toLocaleDateString("en-IN")}`,
      "",
      "MOOD TREND",
      report.trend,
      "",
      "TOP STRESS TRIGGERS",
      report.topTriggers.map((t, i) => `${i + 1}. ${t}`).join("\n"),
      "",
      "WELLNESS TIP",
      report.tip,
      "",
      "ENCOURAGEMENT",
      report.encouragement,
      "",
      "---",
      "Generated by MindEase — Student Wellness Companion",
    ].join("\n");

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mindease-report.txt";
    a.click();
    URL.revokeObjectURL(url);
  }, [report]);

  return (
    <>
      <button
        onClick={() => void fetchReport()}
        className="flex items-center gap-2 rounded-xl border border-[var(--primary-light)] bg-[var(--primary-light)] px-4 py-2.5 text-sm font-semibold text-[var(--primary)] transition hover:bg-indigo-100"
      >
        📊 Get Weekly Report
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-sm">
          <div
            role="dialog"
            aria-modal="true"
            aria-label="Weekly wellness report"
            className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"
          >
            <div className="mb-4 flex items-center justify-between">
              <h2 className="font-heading text-xl font-bold text-[var(--text)]">📊 Weekly Report</h2>
              <button
                onClick={() => setOpen(false)}
                aria-label="Close report"
                className="rounded-full p-1.5 text-gray-400 hover:bg-gray-100 transition"
              >
                ✕
              </button>
            </div>

            {loading && (
              <div className="py-12 text-center">
                <div className="mx-auto mb-4 h-10 w-10 animate-spin rounded-full border-4 border-indigo-100 border-t-[var(--primary)]" />
                <p className="text-sm text-[var(--text-muted)]">Analysing your week…</p>
              </div>
            )}

            {error && (
              <div className="rounded-xl bg-red-50 p-4 text-center text-sm text-red-600">
                {error}
                <button onClick={() => void fetchReport()} className="mt-2 block w-full text-xs underline">
                  Try again
                </button>
              </div>
            )}

            {report && !loading && (
              <div className="space-y-4">
                <div className="rounded-xl bg-[var(--primary-light)] p-4">
                  <p className="mb-1 text-xs font-bold uppercase tracking-wide text-[var(--primary)]">Mood Trend</p>
                  <p className="text-sm text-[var(--text)]">{report.trend}</p>
                </div>
                <div className="rounded-xl bg-gray-50 p-4">
                  <p className="mb-2 text-xs font-bold uppercase tracking-wide text-[var(--text-muted)]">Top Triggers</p>
                  <div className="flex flex-wrap gap-2">
                    {report.topTriggers.map((t) => (
                      <span key={t} className="tag-primary">{t}</span>
                    ))}
                  </div>
                </div>
                <div className="rounded-xl bg-[var(--accent-light)] p-4">
                  <p className="mb-1 text-xs font-bold uppercase tracking-wide text-[var(--accent)]">This Week&apos;s Tip</p>
                  <p className="text-sm text-[var(--text)]">{report.tip}</p>
                </div>
                <div className="rounded-xl bg-amber-50 p-4">
                  <p className="mb-1 text-xs font-bold uppercase tracking-wide text-amber-600">Encouragement</p>
                  <p className="text-sm font-medium text-amber-900">{report.encouragement}</p>
                </div>
                <button
                  onClick={downloadReport}
                  className="btn-primary w-full"
                >
                  ⬇️ Download Report (.txt)
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}
